name: CI-CD Project

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: "18"
            - run: npm install
            - run: npx eslint .

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: "18"
            - run: npm install
            - run: npm test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: "18"
            - run: npm install
            - run: npm run build
    
    docker-deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and Push the Docker  Image
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/CI-CD-PROJECT .
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/CI-CD-PROJECT

